"""Initial migration

Revision ID: 50087f4a2cf7
Revises: 
Create Date: 2019-07-14 22:01:09.074233

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50087f4a2cf7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unpwd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unpwd',
    sa.Column('Username', mysql.CHAR(length=10), nullable=True),
    sa.Column('Password', mysql.CHAR(length=20), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
